version: '3.1'
services:
  app:
    image: "chambre:0.0.1-SNAPSHOT"
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"