spring:
  redis:
    host: localhost
    port: 6379
  session:
    timeout: 1200
    store-type: redis
    redis:
      namespace: chambre

chambre:
  redis:
    expire-sec: 1200
  security:
    cookie:
      secure: false